version: "3.9"

networks:
  back:
    driver: bridge

services:
  app:
    container_name: crud-api
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports: 
      - 3333:3333
    expose:
      - '3333'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    networks:
      - back
  db:
    container_name: postgres-crud
    image: 'postgres:13.1-alpine'
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - data_pg:/data/postgres
    networks:
      - back
volumes:
  data_pg: null